### ISSUE TITLE
Build manylinux1 wheels and autopublish them to PyPI 

### ISSUE THREAD

**Issue by webknjaz** [lxc/python3-lxc#10]
Hi,

I'd like to see this on PyPI with platform-specific wheels. I can send a PR. But before I start I want some confirmation that you'd accept my contribution. I can take care of packaging+travis.

Ref https://github.com/ansible/molecule/issues/1580

@stgraber @brauner

**Comment by brauner** [comment]
Yeah, I think we will take this.

**Comment by stgraber** [comment]
Closing as nothing seems to have happened here.
