### ISSUE TITLE
lxc python api test failed on KVM hosts

### ISSUE THREAD

**Issue by Cypresslin** [lxc/python3-lxc#2]
With a KVM node running with the Xenial KVM kernel (4.4.0-1021-kvm), the python API test in lxc test will failed with interface assertion:

    assert(set(container.get_interfaces()) == set(('lo', 'eth0')))

The actual container.get_interfaces() output on this instance is:

    ('eth0', 'lo', 'sit0')

The extra sit0 cause the problem here.

BugLink: https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1764618

**Comment by brauner** [comment]
On Tue, Apr 17, 2018, 08:47 P.-H. Lin <notifications@github.com> wrote:

> With a KVM node running with the Xenial KVM kernel (4.4.0-1021-kvm), the
> python API test in lxc test will failed with interface assertion:
>
> assert(set(container.get_interfaces()) == set(('lo', 'eth0')))
>
> The actual container.get_interfaces() output on this instance is:
>
> ('eth0', 'lo', 'sit0')
>
> The extra sit0 cause the problem here.
>
> BugLink: https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1764618
>
Is there anything actionable for LXC itself? Doesn't look like there is.

>

**Comment by vicamo** [comment]
Now an additional interface **tunl0** appears inside the container as well when kernel module ipip is inserted in the host side. I think we should include such checks in the `api_test.py`.
