### ISSUE TITLE
publish on PyPI

### ISSUE THREAD

**Issue by TheDiveO** [lxc/python3-lxc#3]
Please publish python3-lxc via PyPI, so it can be properly included in pip/setup.py dependencies without the hassle of having to specify a Git/GitHub dependency (which is a pain in the backside in corporate environments).

**Comment by brauner** [comment]
@stgraber, do you know anything about this?

**Comment by stgraber** [comment]
I don't, some community member did it for the python2 port I tihnk

**Comment by webknjaz** [comment]
@stgraber @brauner I can easily automate this process via Travis CI. It'll require a minimal effort from your side (like create an account on PyPI, encrypt credentials with Travis CI' CLI).
Interested?

**Comment by TheDiveO** [comment]
For me, LXC  and python3 support doesn't matter anymore, as the team has moved to Docker. Not least to the much better API support in multiple language ecosystems. Thank you for the fish.

**Comment by webknjaz** [comment]
For me, it matters, because I wanted to point to the clean dependency...
