### ISSUE TITLE
Build fails as lxc-dev package is missing on macOS

### ISSUE THREAD

**Issue by sourabhtk37** [lxc/python3-lxc#31]
Hi, 

I'm trying to build using `python setup.py build` on macOS. I am greeted with the following error: 
```
lxc.c:27:10: fatal error: 'lxc/lxccontainer.h' file not found
#include <lxc/lxccontainer.h>
         ^~~~~~~~~~~~~~~~~~~~
``` 
This is probably because missing lxc-dev which is not supplied by brew. Could you please help me on how I could resolve this issue?

**Comment by stgraber** [comment]
This can't be built on MacOS, python3-lxc is a binding for liblxc which is a binding for the Linux Containers library, this can't work on non-Linux systems.

(In case that's the confusion, python3-lxc isn't related to LXD, if you're trying to talk to a remote LXD server from python on macOS, look at pylxd instead).
