### ISSUE TITLE
Proxmox support

### ISSUE THREAD

**Issue by mietzen** [lxc/python3-lxc#34]
Would it be possible to also support proxmox?

It can't be installed, since it uses `lxc-pve`:

```
sudo apt install python3-lxc -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lxc-pve : Conflicts: liblxc1
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by stgraber** [comment]
That's not something to do with this repo but purely a packaging issue.

If lxc-pve does ship an identical liblxc1 to the liblxc1 package, then in theory python3-lxc could be packaged to allow that. But since lxc-pve isn't in the Debian archive, that's very unlikely to happen.

**Comment by mietzen** [comment]
Thanks for your reply!
I also realized that this is not in scope of this project. I wanted to `python3-lxc` use it with ansibles lxc connections plugin. 
I now wrote a wrapper around pct: https://github.com/ansible-collections/community.general/pull/8424
