### ISSUE TITLE
lxc keeps config file open

### ISSUE THREAD

**Issue by irnes** [lxc/python3-lxc#4]
I am working on a project for managing an lxc based virtualization platform that relies on this python lxc module. I have noticed that when I create an instance of the lxc container object referencing an existing lxc it keep the underlying lxc config file open during the object's life time. It was not the case in previous versions of LXC. It started from 3.0.0. 

```
~ # python3.5
Python 3.5.5 (default, May 15 2018, 08:59:46) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import lxc
>>> vps = lxc.Container("Test2")
>>> os.getpid()
6975
>>>
```
```

~ # lsof /home/lxc/Test2/config 
COMMAND    PID USER  FD   TYPE DEVICE SIZE/OFF  NODE NAME
python3.5 6975 root mem    REG 230,48     1652 50539 /home/lxc/Test2/config
```

This issue prevent me to migrate to LXC 3.0. I hope this was not an intentional behaviour. Also, I believe this is not related to this python binding but to the lxc core code.

**Comment by brauner** [comment]
What `LXC` version is this with `3.0.0`? If so this should be fixed in `3.0.1`.

**Comment by irnes** [comment]
This is with most recent release 3.0.1. 
```
~ # python3.5
Python 3.5.5 (default, May 15 2018, 08:59:46) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxc
>>> lxc.version
'3.0.1'
>>> 
```

The version 2.1.1 is last one that did not have this problem.

**Comment by irnes** [comment]
I have pulled the master branch and it seems that this has been recently fixed.  So I believe that this will be available in the next release.

Thanks
